#!/usr/bin/env python3
"""
LM Studio Automated Research Script

This script calls LM Studio's local API directly for automated research tasks.
No OpenClaw subagents needed - just direct API calls to LM Studio.
"""

import requests
import json
import sys
from datetime import datetime
from pathlib import Path

# LM Studio API endpoint
LM_STUDIO_URL = "http://localhost:1234/v1/chat/completions"
MODEL = "qwen/qwen3.5-9b"

def call_lm_studio(prompt, max_tokens=2000):
    """Call LM Studio API with a prompt."""
    headers = {
        "Content-Type": "application/json"
    }
    
    data = {
        "model": MODEL,
        "messages": [
            {"role": "system", "content": "You are a research assistant. Provide concise, factual information with sources when possible."},
            {"role": "user", "content": prompt}
        ],
        "max_tokens": max_tokens,
        "temperature": 0.7,
        "top_p": 0.9
    }
    
    try:
        response = requests.post(LM_STUDIO_URL, headers=headers, json=data, timeout=120)
        response.raise_for_status()
        result = response.json()
        return result['choices'][0]['message']['content']
    except Exception as e:
        return f"Error: {str(e)}"

def research_openclaw_updates():
    """Research latest OpenClaw updates."""
    prompt = """Research the latest OpenClaw updates and news. 
    
Search for:
1. Recent OpenClaw releases or announcements
2. New features or changes
3. Community updates

Format your findings as 3-5 bullet points with brief descriptions.
If you don't have current information, say so clearly."""
    
    return call_lm_studio(prompt)

def research_ai_models():
    """Research latest AI model releases."""
    prompt = """Research the latest AI model releases and announcements from major providers (OpenAI, Anthropic, Google, etc.).

Format as:
- **Model Name**: Brief description of capabilities

Provide 3-5 recent notable releases."""
    
    return call_lm_studio(prompt)

def save_research(topic, content):
    """Save research results to memory folder."""
    today = datetime.now().strftime("%Y-%m-%d")
    timestamp = datetime.now().strftime("%Y-%m-%d %H:%M")
    
    # Create memory/research directory if needed
    research_dir = Path.home() / ".openclaw" / "workspace" / "memory" / "research"
    research_dir.mkdir(parents=True, exist_ok=True)
    
    filename = research_dir / f"{today}_{topic}.md"
    
    with open(filename, 'w', encoding='utf-8') as f:
        f.write(f"## {topic.replace('_', ' ').title()} Research - {timestamp}\n\n")
        f.write(content)
        f.write(f"\n\n---\n*Generated by LM Studio (Qwen 3.5) at {timestamp}*\n")
    
    print(f"Saved to: {filename}")
    return filename

def main():
    """Main entry point."""
    if len(sys.argv) < 2:
        print("Usage: python lm_studio_research.py <topic>")
        print("Topics: openclaw, ai_models, test")
        sys.exit(1)
    
    topic = sys.argv[1]
    
    print(f"Starting research: {topic}")
    print(f"Using LM Studio with {MODEL}")
    print("-" * 50)
    
    if topic == "openclaw":
        content = research_openclaw_updates()
    elif topic == "ai_models":
        content = research_ai_models()
    elif topic == "test":
        content = call_lm_studio("Say hello and confirm you're working for automated research tasks.", max_tokens=100)
    else:
        print(f"Unknown topic: {topic}")
        sys.exit(1)
    
    print("\nResearch Result:")
    print("-" * 50)
    print(content)
    print("-" * 50)
    
    if topic != "test":
        filename = save_research(topic, content)
        print(f"\n[OK] Research saved!")
    else:
        print("\n[OK] Test completed!")

if __name__ == "__main__":
    main()
